# Unique project key in SonarQube
sonar.projectKey=jenkins-sonarqube
sonar.projectName=Jenkins SonarQube Project
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Exclusions (optional)
sonar.exclusions=node_modules/**, dist/**, coverage/**

# Code coverage report (optional, if using jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
